// <auto-generated />
namespace SmartStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class promotionchangesproductid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(promotionchangesproductid));
        
        string IMigrationMetadata.Id
        {
            get { return "201710060656273_[promotion-changes-productid]"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
